#!/bin/bash
# NetMonD init script.
# v0.1a 26/11/2012 ~ -idk-
NETMONDPID="/var/run/netmond.pid"

start_netmond(){
/etc/netmond/netmon-daemon >/dev/null 2>&1 & exit 0;
}

case "$1" in
  start)
	if [ -f $NETMONDPID ]; then
		echo "NetMonD dah jalan njing."
	else
		echo "NetMonD is starting."
		start_netmond
	fi;
	exit 1;
	;;
  stop)
	echo "NetMonD is stopping."
	if [ -f $NETMONDPID ]; then
		kill -KILL $(cat $NETMONDPID);
		rm -rf $NETMONDPID;
	fi;
	exit 0;
	;;
  *)
	echo "Cara pake : /etc/init.d/netmond {start|stop}"
	exit 1;
	;;
esac

exit 0;
