#!/bin/bash
# Dig NS server AXFR query tools v0.1b
# v0.1b 01/10/2012 ~ -idk-
# v0.1a 21/08/2012 ~ -idk- 

NS=`dig -t NS $1 +short`;
echo " =====  $1  =====
[+] NS server for $1 domain found :
$NS 
"
for ABI in $NS; do
	UMI=`echo $ABI`;
	VR=`dig @"$UMI" -c CH -t txt version.bind +short`;
	HN=`dig @"$UMI" -c CH -t txt hostname.bind +short`;
	XR=`dig @"$UMI" AXFR $1`;
echo "
[+] Enumerating $UMI server...
[+] NS server version       : $VR 
[+] NS server hostname      : $HN 
[+] Querying $UMI server    : $XR
"
sleep 3;
done
