#!/bin/bash
# Copyleft (c) -idk- 12/07/2012
URI="https://www.pandi.or.id/whois/whois.php"
PDATA="domain=$1&submit=Whois+Lookup"
TMP="/tmp/whoisid-$1"; echo [Querying pandi.or.id]
GET=`curl -s -k $URI -d $PDATA > $TMP`;
DNAME="$1";
DCREATE=`grep "Created On:" $TMP | head -1 | cut -d":" -f2,3`;
DUPDATE=`grep "Last Updated On:" $TMP | head -1 | cut -d":" -f2,3`;
DEXPIRE=`grep "Expiration Date:" $TMP | head -1 | cut -d":" -f2,3`;
DINAME=`grep "Billing Name:" $TMP | head -1 | cut -d":" -f4`;
DEMAIL=`grep "Billing Email:" $TMP | head -1 | cut -d":" -f2`;
DTLP=`grep "Billing Phone:" $TMP | head -1 | cut -d":" -f2`;

echo "[+] Whois Results for "$1"."
echo "[+] Nama domainnya        : "$DNAME
echo "[+] Tanggal daptarnya     : "$DCREATE
echo "[+] Tanggal perpanjangnya : "$DUPDATE
echo "[+] Tanggal abisnya       : "$DEXPIRE
echo "[+] Nama yg punyanya      : "$DINAME
echo "[+] Email yg punyanya     : "$DEMAIL
echo "[+] Mau telpon punyanya   : "$DTLP
if [ "$DINAME" = "arif wicaksono" ]; then
echo "[+] Calon istrinya        : Orang Batam"
fi

shred -uz $TMP
